import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import PageLayout from 'pages/layouts/PageLayout'
import { ReactElement } from 'react'

import { NextPageWithLayout } from 'types/app.types'

const MoviePage: NextPageWithLayout = () => {
  const router = useRouter()

  console.log(router.query);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>MOVIEPage</p>
    </div>
  )
}

MoviePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <PageLayout>
      {page}
    </PageLayout>
  )
}

export default MoviePage
