import { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import { Fragment } from 'react'
import styles from '../styles/Home.module.css'

import Api from 'api'
import { Article } from 'types/article.types'

export const getStaticProps: GetStaticProps = async (context) => {
  console.log('getStaticProps')
  console.log(context)

  const articlesResponse = await Api.getArticles()

  return {
    props: {
      articles: articlesResponse.data
    }
  }
}

const Home: NextPage = ({ articles }: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log(articles)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          {(articles as Array<Article>).map((article) => (
            <Fragment key={article._id}>
              <h1>{article.title}</h1>
              <p>{article.intro}</p>
            </Fragment>
          ))}
        </div>
      </main>


    </div>
  )
}

export default Home
